/**
 * Realistic mock hunt data used in the overlay editor
 * so widgets display with placeholder content.
 */

export const MOCK_HUNT_DATA = {
  title: "Friday Night Bonus Hunt #47",
  status: "active",
  totalCost: "4250.00",
  totalWon: "6832.50",
  entries: [
    {
      id: "mock-1",
      gameName: "Gates of Olympus",
      gameImage: null,
      gameProvider: "Pragmatic Play",
      betSize: "2.00",
      cost: "200.00",
      result: "1842.00",
      multiplier: "921.00",
      status: "completed",
    },
    {
      id: "mock-2",
      gameName: "Sweet Bonanza",
      gameImage: null,
      gameProvider: "Pragmatic Play",
      betSize: "1.00",
      cost: "100.00",
      result: "456.50",
      multiplier: "456.50",
      status: "completed",
    },
    {
      id: "mock-3",
      gameName: "Wanted Dead or a Wild",
      gameImage: null,
      gameProvider: "Hacksaw Gaming",
      betSize: "0.40",
      cost: "40.00",
      result: "312.80",
      multiplier: "782.00",
      status: "completed",
    },
    {
      id: "mock-4",
      gameName: "Sugar Rush",
      gameImage: null,
      gameProvider: "Pragmatic Play",
      betSize: "1.00",
      cost: "100.00",
      result: "43.20",
      multiplier: "43.20",
      status: "completed",
    },
    {
      id: "mock-5",
      gameName: "Razor Shark",
      gameImage: null,
      gameProvider: "Push Gaming",
      betSize: "0.50",
      cost: "50.00",
      result: "675.00",
      multiplier: "1350.00",
      status: "completed",
    },
    {
      id: "mock-6",
      gameName: "Mental",
      gameImage: null,
      gameProvider: "Nolimit City",
      betSize: "0.20",
      cost: "20.00",
      result: "8.40",
      multiplier: "42.00",
      status: "completed",
    },
    {
      id: "mock-7",
      gameName: "Book of Dead",
      gameImage: null,
      gameProvider: "Play'n GO",
      betSize: "2.00",
      cost: "200.00",
      result: "890.00",
      multiplier: "445.00",
      status: "completed",
    },
    {
      id: "mock-8",
      gameName: "Fruit Party",
      gameImage: null,
      gameProvider: "Pragmatic Play",
      betSize: "1.00",
      cost: "100.00",
      result: "24.50",
      multiplier: "24.50",
      status: "completed",
    },
    {
      id: "mock-9",
      gameName: "Starlight Princess",
      gameImage: null,
      gameProvider: "Pragmatic Play",
      betSize: "0.50",
      cost: "50.00",
      result: "1580.00",
      multiplier: "3160.00",
      status: "completed",
    },
    {
      id: "mock-10",
      gameName: "Big Bass Bonanza",
      gameImage: null,
      gameProvider: "Pragmatic Play",
      betSize: "2.00",
      cost: "200.00",
      result: null,
      multiplier: null,
      status: "playing",
    },
    {
      id: "mock-11",
      gameName: "San Quentin",
      gameImage: null,
      gameProvider: "Nolimit City",
      betSize: "0.20",
      cost: "20.00",
      result: null,
      multiplier: null,
      status: "pending",
    },
    {
      id: "mock-12",
      gameName: "Fire in the Hole",
      gameImage: null,
      gameProvider: "Nolimit City",
      betSize: "0.40",
      cost: "40.00",
      result: null,
      multiplier: null,
      status: "pending",
    },
    {
      id: "mock-13",
      gameName: "Tombstone RIP",
      gameImage: null,
      gameProvider: "Nolimit City",
      betSize: "0.20",
      cost: "20.00",
      result: null,
      multiplier: null,
      status: "pending",
    },
    {
      id: "mock-14",
      gameName: "The Dog House",
      gameImage: null,
      gameProvider: "Pragmatic Play",
      betSize: "1.00",
      cost: "100.00",
      result: null,
      multiplier: null,
      status: "pending",
    },
    {
      id: "mock-15",
      gameName: "Retro Tapes",
      gameImage: null,
      gameProvider: "Push Gaming",
      betSize: "1.00",
      cost: "100.00",
      result: null,
      multiplier: null,
      status: "pending",
    },
  ],
};
